### ISSUE TITLE
split into header / content / sidebar / footer

### ISSUE THREAD

**Issue by Kazhnuz** [Quarante-Douze/qdouze-wordpress-theme#2]
- [x] Add header.php #3 
- [x] Add sidebar.php #7 
- [x] Add footer.php #6

**Comment by Kazhnuz** [comment]
Fixed by fixing #3
