### ISSUE TITLE
Header meta-issue

### ISSUE THREAD

**Issue by Kazhnuz** [Quarante-Douze/qdouze-wordpress-theme#3]
- [x] add pages navebar
- [x] add categories navebar
- [x] add search box
- [x] meta support
- [x] Make link works correctly #19 

Block #2

**Comment by Kazhnuz** [comment]
Fixed by d540cee847d2084684003385b5de775f53371dd5
